# fly.toml app configuration file generated for app-dt-25-6-3-1719375445-client on 2024-06-26T04:18:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-dt-25-6-3-1719375445-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
